// @vitest-environment node
/**
 * The engine against three independent oracles over 1,000 seeded configurations.
 *
 * The fixture is generated by tools/oracles/generate.mjs: every case was computed by each oracle in its
 * `oracles` list (always tools/reference_enigma.py, plus @ondoher/enigma 1.0.14 and, where it supports
 * the configuration, py-enigma 1.0.2), and they all agreed on the ciphertext and the final windows.
 * Here the engine must reproduce every case. The oracles themselves are not needed to run this suite.
 * Regenerate with `cd tools/oracles && npm ci && node generate.mjs` (never edit the JSON by hand).
 */

import { describe, expect, it } from 'vitest'
import fixture from '../__fixtures__/oracle-vectors.json'
import {
  LETTERS,
  MODELS,
  MODEL_NAMES,
  REFLECTOR_NAMES,
  createMachine,
  encipher,
  positionsToString,
  pressKey,
  type MachineConfig,
  type ModelName,
} from '../index'

type OracleName = 'reference' | 'ondoher' | 'pyEnigma'

interface OracleCase {
  id: string
  config: MachineConfig
  plaintext: string
  ciphertext: string
  finalPositions: string
  oracles: OracleName[]
}

interface OracleFixture {
  seed: number
  oracles: Record<OracleName, string>
  cases: OracleCase[]
}

const data = fixture as unknown as OracleFixture
const cases = data.cases
const ORACLE_NAMES: readonly OracleName[] = ['reference', 'ondoher', 'pyEnigma']
const LONG = 1000

function label(c: OracleCase): string {
  const { model, reflector, rotors, rings, positions, plugboard } = c.config
  return (
    `${c.id} ${model} UKW-${reflector} ${rotors.join('-')} rings ${rings.join('')} at ${positions.join('')}, ` +
    `${plugboard.length} plugs, ${c.plaintext.length} letters [${c.oracles.join('+')}]`
  )
}

describe('oracle agreement fixture (web/src/engine/__fixtures__/oracle-vectors.json)', () => {
  it('holds 1,000 unique cases: 200 texts of 1,000 letters and 800 of 20–60', () => {
    expect(data.seed).toBe(20260928)
    expect(cases).toHaveLength(1000)
    expect(new Set(cases.map((c) => c.id)).size).toBe(cases.length)
    const long = cases.filter((c) => c.plaintext.length === LONG)
    expect(long).toHaveLength(200)
    for (const c of cases) {
      if (c.plaintext.length !== LONG) {
        expect(c.plaintext.length).toBeGreaterThanOrEqual(20)
        expect(c.plaintext.length).toBeLessThanOrEqual(60)
      }
      expect(c.plaintext).toMatch(/^[A-Z]+$/)
      expect(c.ciphertext).toHaveLength(c.plaintext.length)
    }
  })

  it('lists at least two agreeing oracles per case, always including the reference', () => {
    for (const c of cases) {
      expect(c.oracles[0], c.id).toBe('reference')
      expect(c.oracles.length, c.id).toBeGreaterThanOrEqual(2)
      expect(new Set(c.oracles).size, c.id).toBe(c.oracles.length)
      for (const o of c.oracles) expect(ORACLE_NAMES, c.id).toContain(o)
    }
    // Every oracle is present in the file, and py-enigma is actually used (not a CI-only placeholder).
    for (const o of ORACLE_NAMES) expect(cases.some((c) => c.oracles.includes(o))).toBe(true)
  })

  it('covers every model, rotor and reflector, the A and Z ring extremes and 0–13 plug pairs', () => {
    const byModel = (m: ModelName) => cases.filter((c) => c.config.model === m)
    for (const model of MODEL_NAMES) {
      const own = byModel(model)
      expect(own.length, model).toBeGreaterThan(300)
      const used = new Set(own.flatMap((c) => c.config.rotors))
      for (const rotor of [...MODELS[model].rotors, ...MODELS[model].greekRotors]) expect(used, model).toContain(rotor)
      const reflectors = new Set(own.map((c) => c.config.reflector))
      for (const reflector of MODELS[model].reflectors) expect(reflectors, model).toContain(reflector)
      // Each model is checked by all three oracles somewhere, not only by the reference and one other.
      for (const o of ORACLE_NAMES) expect(own.some((c) => c.oracles.includes(o)), `${model} ${o}`).toBe(true)
    }
    expect(new Set(cases.map((c) => c.config.reflector))).toEqual(new Set(REFLECTOR_NAMES))
    const allRings = (letter: string) => cases.some((c) => c.config.rings.every((r) => r === letter))
    expect(allRings('A')).toBe(true)
    expect(allRings('Z')).toBe(true)
    const plugCounts = new Set(cases.map((c) => c.config.plugboard.length))
    for (let k = 0; k <= 13; k++) expect(plugCounts, `${k} plug pairs`).toContain(k)
    for (const letter of LETTERS) expect(cases.some((c) => c.config.positions.includes(letter))).toBe(true)
  })
})

describe('the engine reproduces every oracle case', () => {
  it.each(cases.map((c) => [label(c), c] as const))('%s', (_, c) => {
    const start = createMachine(c.config)
    const enc = encipher(start, c.plaintext)
    expect(enc.output).toBe(c.ciphertext)
    expect(positionsToString(enc.state)).toBe(c.finalPositions)
    // Self-reciprocal: the same start state deciphers.
    expect(encipher(start, c.ciphertext).output).toBe(c.plaintext)
    // The traced key-by-key path used by the UI agrees with the fast path (short texts keep it quick).
    if (c.plaintext.length !== LONG) {
      let s = start
      let out = ''
      for (const ch of c.plaintext) {
        const r = pressKey(s, ch)
        s = r.state
        out += r.output
      }
      expect(out).toBe(c.ciphertext)
      expect(positionsToString(s)).toBe(c.finalPositions)
    }
  })
})
